<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SimplestEngine.Resources</RootNamespace>
    <AssemblyName>SimplestEngine.Resources</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplestEngine.Core\SimplestEngine.Core.csproj" />
    <ProjectReference Include="..\SimplestEngine.Abi\SimplestEngine.Abi.csproj" />
    <ProjectReference Include="..\SimplestEngine.Scene\SimplestEngine.Scene.csproj" />
  </ItemGroup>
</Project>
