<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SimplestEngine.Platform</RootNamespace>
    <AssemblyName>SimplestEngine.Platform</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
    <PackageReference Include="Veldrid" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimplestEngine.Core\SimplestEngine.Core.csproj" />
    <ProjectReference Include="..\SimplestEngine.Abi\SimplestEngine.Abi.csproj" />
  </ItemGroup>
</Project>
